CREATE TABLE [dbo].[Person] (
    [PersonID]          INT           IDENTITY (1, 1) NOT NULL,
    [OrganizationID]    INT           NULL,
    [TitleID]           INT           NULL,
    [GivenName]         VARCHAR (100) NOT NULL,
    [FamilyName]        VARCHAR (100) NOT NULL,
    [IdentityTypeID]    INT           NULL,
    [IdentityNumber]    VARCHAR (20)  NULL,
    [PassportNumber]    VARCHAR (100) NULL,
    [PassportCountryID] INT           NULL,
    [TaxID]             VARCHAR (20)  NULL,
    [BirthDate]         DATE          NULL,
    [BirthPlace]        VARCHAR (100) NULL,
    [Telephone]         NUMERIC (18)  NOT NULL,
    [FaxNumber]         NUMERIC (18)  NULL,
    [MobileNumber]      NUMERIC (18)  NULL,
    [Email]             VARCHAR (100) NULL,
    [JobTitleID]        INT           NULL,
    [Verified]          BIT           NOT NULL,
    [DateCreated]       DATETIME      NOT NULL,
    [DateModified]      DATETIME      NULL,
    [Deleted]           BIT           NOT NULL,
    CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED ([PersonID] ASC),
    CONSTRAINT [FK_Person_Country] FOREIGN KEY ([PassportCountryID]) REFERENCES [dbo].[Country] ([CountryID]),
    CONSTRAINT [FK_Person_IdentityType] FOREIGN KEY ([IdentityTypeID]) REFERENCES [dbo].[IdentityType] ([IdentityTypeID]),
    CONSTRAINT [FK_Person_JobTitle] FOREIGN KEY ([JobTitleID]) REFERENCES [dbo].[JobTitle] ([JobTitleID]),
    CONSTRAINT [FK_Person_Organization] FOREIGN KEY ([OrganizationID]) REFERENCES [dbo].[Organization] ([OrganizationID]),
    CONSTRAINT [FK_Person_Title] FOREIGN KEY ([TitleID]) REFERENCES [dbo].[Title] ([TitleID])
);

