CREATE TABLE [dbo].[User] (
    [UserID]            INT            IDENTITY (1, 1) NOT NULL,
    [EntityID]          INT            NULL,
    [TitleID]           INT            NOT NULL,
    [GivenName]         VARCHAR (100)  NOT NULL,
    [FamilyName]        VARCHAR (100)  NOT NULL,
    [IdentityNumber]    VARCHAR (20)   NOT NULL,
    [PassportNumber]    VARCHAR (100)  NULL,
    [PassportCountryID] INT            NULL,
    [TaxID]             VARCHAR (20)   NULL,
    [BirthDate]         DATE           NOT NULL,
    [BirthPlace]        VARCHAR (100)  NULL,
    [Telephone]         NUMERIC (18)   NULL,
    [MobileNumber]      NUMERIC (18)   NULL,
    [FaxNumber]         NUMERIC (18)   NULL,
    [Email]             VARCHAR (100)  NULL,
    [JobTitleID]        INT            NULL,
    [Verified]          BIT            NOT NULL,
    [DateCreated]       DATETIME       NOT NULL,
    [DateModified]      DATETIME       NULL,
    [Deleted]           BIT            NOT NULL,
    [HeaderTabToggle]   BIT            NULL,
    [pwd]               VARCHAR (MAX)  NULL,
    [TokenId]           VARCHAR (MAX)  NULL,
    [AspNetUsersId]     NVARCHAR (128) NULL,
    [ProfilePicture]    NVARCHAR (MAX) NULL,
    [WorkflowID]        INT            NULL,
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([UserID] ASC),
    CONSTRAINT [FK_User_Country] FOREIGN KEY ([PassportCountryID]) REFERENCES [dbo].[Country] ([CountryID]),
    CONSTRAINT [FK_User_Entity] FOREIGN KEY ([EntityID]) REFERENCES [dbo].[Entity] ([EntityID]),
    CONSTRAINT [FK_User_JobTitle] FOREIGN KEY ([JobTitleID]) REFERENCES [dbo].[JobTitle] ([JobTitleID])
);

