//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerts
    {
        public long ID { get; set; }
        public Nullable<int> DealID { get; set; }
        public Nullable<int> AlertTypeID { get; set; }
        public int StatusID { get; set; }
        public string EventName { get; set; }
        public string Location { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Comment { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> AlertsGUID { get; set; }
    
        public virtual AlertStatus AlertStatus { get; set; }
        public virtual AlertType AlertType { get; set; }
        public virtual Deal Deal { get; set; }
        public virtual User User { get; set; }
    }
}
