//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingRateDetail
    {
        public long BillingRateDetailID { get; set; }
        public int TierNumber { get; set; }
        public decimal StartValue { get; set; }
        public decimal EndValue { get; set; }
        public int CurrencyID { get; set; }
        public string Value { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CurrencyType CurrencyType { get; set; }
    }
}
