//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public long BillingID { get; set; }
        public string KeyName { get; set; }
        public int ForeignKey { get; set; }
        public long BillingRateID { get; set; }
        public string UniqueReference { get; set; }
        public int InvoiceToUserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool Deleted { get; set; }
    
        public virtual BillingRate BillingRate { get; set; }
    }
}
