//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correspondence
    {
        public int ID { get; set; }
        public long TransactionID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime MessageDate { get; set; }
        public bool Incoming { get; set; }
        public string Subject { get; set; }
        public string Headers { get; set; }
        public string Text { get; set; }
        public string Html { get; set; }
        public string Body { get; set; }
        public bool Hidden { get; set; }
        public int SmtpStatusID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string MessageID { get; set; }
        public Nullable<int> AttachmentID { get; set; }
        public Nullable<System.Guid> CorrespondenceGUID { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
