//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentWorkflow
    {
        public int ID { get; set; }
        public Nullable<int> DocumentVersionID { get; set; }
        public Nullable<int> WorkflowStepID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
