//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTemplate
    {
        public int ID { get; set; }
        public string TemplateDisplayName { get; set; }
        public Nullable<int> DocumentVersionID { get; set; }
        public string AttributeName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsDocfusionTemplate { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.Guid> TemplateFixGUID { get; set; }
    }
}
