//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.TransactionDocuments = new HashSet<TransactionDocuments>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DealID { get; set; }
        public Nullable<int> DocumentTemplateID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public string GeneratedDocFileName { get; set; }
        public string FileHash { get; set; }
        public string MimeTypeID { get; set; }
        public string SignedDocFileName { get; set; }
        public string SignedDocMimeTypeID { get; set; }
        public Nullable<System.DateTime> SignedDocDate { get; set; }
        public string SignedDocHash { get; set; }
        public Nullable<int> SignedUploadedByUserID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> WorkflowStepID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDocuments> TransactionDocuments { get; set; }
    }
}
