//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentVersion
    {
        public int ID { get; set; }
        public Nullable<int> DocumentTypeID { get; set; }
        public string VersionName { get; set; }
        public string TemplateFileName { get; set; }
        public string Comments { get; set; }
        public string MimeTypeID { get; set; }
        public string XMLStoredProc { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<bool> eSignable { get; set; }
        public Nullable<bool> IsStaticDoc { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
