//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialObligation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialObligation()
        {
            this.FinancialObligationDetail = new HashSet<FinancialObligationDetail>();
        }
    
        public int ObligationID { get; set; }
        public int ParticipantID { get; set; }
        public int CurrencyID { get; set; }
        public decimal Value { get; set; }
        public string LegalDescription { get; set; }
        public decimal AccountBalance { get; set; }
        public decimal AccountNumber { get; set; }
        public int InterestVariationID { get; set; }
        public int InterestTypeID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool Deleted { get; set; }
    
        public virtual FinancialObligation FinancialObligation1 { get; set; }
        public virtual FinancialObligation FinancialObligation2 { get; set; }
        public virtual InterestType InterestType { get; set; }
        public virtual InterestVariation InterestVariation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialObligationDetail> FinancialObligationDetail { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
