//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialInstrumentDetail
    {
        public int InstrumentDetailID { get; set; }
        public int InstrumentID { get; set; }
        public int InstrumentTypeID { get; set; }
        public int InterestVariationID { get; set; }
        public int InterestTypeID { get; set; }
        public int CurrencyTypeID { get; set; }
        public decimal Value { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CurrencyType CurrencyType { get; set; }
        public virtual InstrumentType InstrumentType { get; set; }
        public virtual InterestType InterestType { get; set; }
        public virtual InterestVariation InterestVariation { get; set; }
    }
}
