//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialTransaction
    {
        public int FinancialTransactionID { get; set; }
        public int DealID { get; set; }
        public Nullable<int> ObligationID { get; set; }
        public int InstrumentID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Deal Deal { get; set; }
        public virtual FinancialInstrument FinancialInstrument { get; set; }
    }
}
