//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialObligationDetail
    {
        public int ObligationDetailID { get; set; }
        public int ObligationID { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public decimal Value { get; set; }
        public Nullable<decimal> InstalmentValue { get; set; }
        public Nullable<decimal> WaivedPercentage { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool Deleted { get; set; }
    
        public virtual FinancialObligation FinancialObligation { get; set; }
    }
}
