//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialInstrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialInstrument()
        {
            this.FinancialTransaction = new HashSet<FinancialTransaction>();
        }
    
        public int InstrumentID { get; set; }
        public Nullable<int> ParticipantID { get; set; }
        public Nullable<int> CurrencyTypeID { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public string Term { get; set; }
        public int LenderID { get; set; }
        public int InstrumentTypeID { get; set; }
        public int InterestTypeID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.Guid> InstrumentGUID { get; set; }
    
        public virtual InstrumentType InstrumentType { get; set; }
        public virtual InterestType InterestType { get; set; }
        public virtual Lenders Lenders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialTransaction> FinancialTransaction { get; set; }
    }
}
