//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmDetails
    {
        public int FirmID { get; set; }
        public string FirmName { get; set; }
        public string FirmAddress { get; set; }
        public string FirmTelNo { get; set; }
        public string FirmFaxNo { get; set; }
        public string FirmwebURL { get; set; }
        public string DirectorName { get; set; }
        public string DirectorSurname { get; set; }
        public string CCManagerName { get; set; }
        public string CCManagerSurname { get; set; }
        public string CCTitle { get; set; }
        public string CCContactNumber { get; set; }
        public string CCEmail { get; set; }
        public string CCAddress { get; set; }
        public string CCWeb { get; set; }
    }
}
