//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participant()
        {
            this.FinancialObligation = new HashSet<FinancialObligation>();
            this.ParticipantBankDetail = new HashSet<ParticipantBankDetail>();
            this.UserDocument = new HashSet<UserDocument>();
        }
    
        public int ParticipantID { get; set; }
        public int DealID { get; set; }
        public int ParticipantTypeID { get; set; }
        public Nullable<int> ParticipantRoleID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> BankID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.Guid> ParticipantGUID { get; set; }
        public Nullable<int> EntityID { get; set; }
    
        public virtual BankorCreditUnion BankorCreditUnion { get; set; }
        public virtual Deal Deal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialObligation> FinancialObligation { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ParticipantRole ParticipantRole { get; set; }
        public virtual ParticipantType ParticipantType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantBankDetail> ParticipantBankDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDocument> UserDocument { get; set; }
    }
}
