//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantBankDetail
    {
        public int ID { get; set; }
        public int ParticipantID { get; set; }
        public int BankID { get; set; }
        public int AccountTypeID { get; set; }
        public string AccountName { get; set; }
        public decimal AccountNumber { get; set; }
        public decimal SortCode { get; set; }
        public bool Verified { get; set; }
        public bool Deleted { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual BankorCreditUnion BankorCreditUnion { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
