//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyDetail
    {
        public int PropertyDetailID { get; set; }
        public int PropertyID { get; set; }
        public Nullable<int> RightTypeID { get; set; }
        public string PropertyNumber { get; set; }
        public string PortionNumber { get; set; }
        public string Township { get; set; }
        public string PropertyName { get; set; }
        public string RegistrationDivision { get; set; }
        public string SectionNumber { get; set; }
        public string PlanNumber { get; set; }
        public Nullable<int> UnitNumber { get; set; }
        public int SizeTypeID { get; set; }
        public string Size { get; set; }
        public string Geo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.Guid> PropertyDetailGUID { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual SizeType SizeType { get; set; }
    }
}
