//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportLocation
    {
        public int reportLocationID { get; set; }
        public string Location { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> ReportsId { get; set; }
        public string ChartType { get; set; }
        public string ChartName { get; set; }
    }
}
