//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public System.Guid TaskGUID { get; set; }
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public string TaskDisplayIcon { get; set; }
        public string TaskControl { get; set; }
        public Nullable<int> TaskWorkflowID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsWorkflowTask { get; set; }
    }
}
