//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Township
    {
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string DateModified { get; set; }
        public bool Deleted { get; set; }
        public int TownshipID { get; set; }
    }
}
