//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow
    {
        public System.Guid WorkflowGUID { get; set; }
        public int WorkflowID { get; set; }
        public string WorkflowName { get; set; }
        public bool IsDeleted { get; set; }
    }
}
