//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowProgress
    {
        public System.Guid WorkflowProgressGUID { get; set; }
        public long WorkflowProgressID { get; set; }
        public int DealID { get; set; }
        public int WorkflowTaskID { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public Nullable<int> WorkflowParentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
