//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPS.DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowTransaction
    {
        public long ID { get; set; }
        public int WorkflowActionID { get; set; }
        public long TransactionID { get; set; }
        public bool IsDeleted { get; set; }
    }
}
